[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "pynacl>=1.5.0",
    "requests>=2.32.4",
    "uuid>=1.30",
    "yt-dlp>=2025.8.20",
]
